# Generated by Django 2.0.5 on 2018-05-30 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('thumb', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=300)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epigraph', models.TextField()),
                ('title', models.TextField()),
                ('subhead', models.TextField()),
                ('copy', models.TextField()),
                ('slug', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Category')),
                ('feature_media', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.FeatureMedia')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.News')),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='newstags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.NewsType'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Status'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.MediaType'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Media'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.News'),
        ),
        migrations.AddField(
            model_name='featuremedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Media'),
        ),
    ]
