# Generated by Django 2.0.5 on 2018-06-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CoverNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Cover')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.News')),
            ],
        ),
    ]
